wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    code_path: code/nd_lang/lab1/training/run_experiment2.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.8.8
      5: 0.10.25
      8:
      - 5
dataset:
  desc: null
  value: HousingData
epoch:
  desc: null
  value: 10
model:
  desc: null
  value: <lab1.language_model.models.base2.Model object at 0x7fbbf34d0370>
network:
  desc: null
  value: mlp
train_args:
  desc: null
  value:
    batch_size: 64
    epochs: 16
