wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.26
    code_path: code/nd_lang/lab1/training/run_experiment2.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.8.8
      5: 0.10.26
      8:
      - 5
activation-fn:
  desc: null
  value: relu
epochs:
  desc: null
  value: 15
name:
  desc: null
  value: Blessing
surname:
  desc: null
  value: Chitakatira
